/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPrazosRouteImport } from './routes/_authenticated/prazos'
import { Route as AuthenticatedPautaAudienciasRouteImport } from './routes/_authenticated/pauta-audiencias'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedNovoProcessoRouteImport } from './routes/_authenticated/novo-processo'
import { Route as AuthenticatedNaoProtocoladosRouteImport } from './routes/_authenticated/nao-protocolados'
import { Route as AuthenticatedMeusProcessosRouteImport } from './routes/_authenticated/meus-processos'
import { Route as AuthenticatedIntimacoesRouteImport } from './routes/_authenticated/intimacoes'
import { Route as AuthenticatedHabilitacoesPendentesRouteImport } from './routes/_authenticated/habilitacoes-pendentes'
import { Route as AuthenticatedHabilitacaoRouteImport } from './routes/_authenticated/habilitacao'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedBnmpRouteImport } from './routes/_authenticated/bnmp'
import { Route as AuthenticatedProcessosIndexRouteImport } from './routes/_authenticated/processos.index'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as AuthenticatedConsultasSistemaRouteImport } from './routes/_authenticated/consultas.$sistema'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'

const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrazosRoute = AuthenticatedPrazosRouteImport.update({
  id: '/prazos',
  path: '/prazos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPautaAudienciasRoute =
  AuthenticatedPautaAudienciasRouteImport.update({
    id: '/pauta-audiencias',
    path: '/pauta-audiencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoProcessoRoute =
  AuthenticatedNovoProcessoRouteImport.update({
    id: '/novo-processo',
    path: '/novo-processo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNaoProtocoladosRoute =
  AuthenticatedNaoProtocoladosRouteImport.update({
    id: '/nao-protocolados',
    path: '/nao-protocolados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusProcessosRoute =
  AuthenticatedMeusProcessosRouteImport.update({
    id: '/meus-processos',
    path: '/meus-processos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntimacoesRoute = AuthenticatedIntimacoesRouteImport.update({
  id: '/intimacoes',
  path: '/intimacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabilitacoesPendentesRoute =
  AuthenticatedHabilitacoesPendentesRouteImport.update({
    id: '/habilitacoes-pendentes',
    path: '/habilitacoes-pendentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHabilitacaoRoute =
  AuthenticatedHabilitacaoRouteImport.update({
    id: '/habilitacao',
    path: '/habilitacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBnmpRoute = AuthenticatedBnmpRouteImport.update({
  id: '/bnmp',
  path: '/bnmp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessosIndexRoute =
  AuthenticatedProcessosIndexRouteImport.update({
    id: '/processos/',
    path: '/processos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/processos/$id',
    path: '/processos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultasSistemaRoute =
  AuthenticatedConsultasSistemaRouteImport.update({
    id: '/consultas/$sistema',
    path: '/consultas/$sistema',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consulta': typeof ConsultaRoute
  '/bnmp': typeof AuthenticatedBnmpRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/habilitacao': typeof AuthenticatedHabilitacaoRoute
  '/habilitacoes-pendentes': typeof AuthenticatedHabilitacoesPendentesRoute
  '/intimacoes': typeof AuthenticatedIntimacoesRoute
  '/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/nao-protocolados': typeof AuthenticatedNaoProtocoladosRoute
  '/novo-processo': typeof AuthenticatedNovoProcessoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pauta-audiencias': typeof AuthenticatedPautaAudienciasRoute
  '/prazos': typeof AuthenticatedPrazosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/consultas/$sistema': typeof AuthenticatedConsultasSistemaRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consulta': typeof ConsultaRoute
  '/bnmp': typeof AuthenticatedBnmpRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/habilitacao': typeof AuthenticatedHabilitacaoRoute
  '/habilitacoes-pendentes': typeof AuthenticatedHabilitacoesPendentesRoute
  '/intimacoes': typeof AuthenticatedIntimacoesRoute
  '/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/nao-protocolados': typeof AuthenticatedNaoProtocoladosRoute
  '/novo-processo': typeof AuthenticatedNovoProcessoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pauta-audiencias': typeof AuthenticatedPautaAudienciasRoute
  '/prazos': typeof AuthenticatedPrazosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/consultas/$sistema': typeof AuthenticatedConsultasSistemaRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/processos': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/consulta': typeof ConsultaRoute
  '/_authenticated/bnmp': typeof AuthenticatedBnmpRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/habilitacao': typeof AuthenticatedHabilitacaoRoute
  '/_authenticated/habilitacoes-pendentes': typeof AuthenticatedHabilitacoesPendentesRoute
  '/_authenticated/intimacoes': typeof AuthenticatedIntimacoesRoute
  '/_authenticated/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/_authenticated/nao-protocolados': typeof AuthenticatedNaoProtocoladosRoute
  '/_authenticated/novo-processo': typeof AuthenticatedNovoProcessoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pauta-audiencias': typeof AuthenticatedPautaAudienciasRoute
  '/_authenticated/prazos': typeof AuthenticatedPrazosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/consultas/$sistema': typeof AuthenticatedConsultasSistemaRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/_authenticated/processos/': typeof AuthenticatedProcessosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/consulta'
    | '/bnmp'
    | '/diario'
    | '/habilitacao'
    | '/habilitacoes-pendentes'
    | '/intimacoes'
    | '/meus-processos'
    | '/nao-protocolados'
    | '/novo-processo'
    | '/painel'
    | '/pauta-audiencias'
    | '/prazos'
    | '/admin/usuarios'
    | '/consultas/$sistema'
    | '/processos/$id'
    | '/processos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/consulta'
    | '/bnmp'
    | '/diario'
    | '/habilitacao'
    | '/habilitacoes-pendentes'
    | '/intimacoes'
    | '/meus-processos'
    | '/nao-protocolados'
    | '/novo-processo'
    | '/painel'
    | '/pauta-audiencias'
    | '/prazos'
    | '/admin/usuarios'
    | '/consultas/$sistema'
    | '/processos/$id'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/consulta'
    | '/_authenticated/bnmp'
    | '/_authenticated/diario'
    | '/_authenticated/habilitacao'
    | '/_authenticated/habilitacoes-pendentes'
    | '/_authenticated/intimacoes'
    | '/_authenticated/meus-processos'
    | '/_authenticated/nao-protocolados'
    | '/_authenticated/novo-processo'
    | '/_authenticated/painel'
    | '/_authenticated/pauta-audiencias'
    | '/_authenticated/prazos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/consultas/$sistema'
    | '/_authenticated/processos/$id'
    | '/_authenticated/processos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsultaRoute: typeof ConsultaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prazos': {
      id: '/_authenticated/prazos'
      path: '/prazos'
      fullPath: '/prazos'
      preLoaderRoute: typeof AuthenticatedPrazosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pauta-audiencias': {
      id: '/_authenticated/pauta-audiencias'
      path: '/pauta-audiencias'
      fullPath: '/pauta-audiencias'
      preLoaderRoute: typeof AuthenticatedPautaAudienciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-processo': {
      id: '/_authenticated/novo-processo'
      path: '/novo-processo'
      fullPath: '/novo-processo'
      preLoaderRoute: typeof AuthenticatedNovoProcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nao-protocolados': {
      id: '/_authenticated/nao-protocolados'
      path: '/nao-protocolados'
      fullPath: '/nao-protocolados'
      preLoaderRoute: typeof AuthenticatedNaoProtocoladosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-processos': {
      id: '/_authenticated/meus-processos'
      path: '/meus-processos'
      fullPath: '/meus-processos'
      preLoaderRoute: typeof AuthenticatedMeusProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intimacoes': {
      id: '/_authenticated/intimacoes'
      path: '/intimacoes'
      fullPath: '/intimacoes'
      preLoaderRoute: typeof AuthenticatedIntimacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habilitacoes-pendentes': {
      id: '/_authenticated/habilitacoes-pendentes'
      path: '/habilitacoes-pendentes'
      fullPath: '/habilitacoes-pendentes'
      preLoaderRoute: typeof AuthenticatedHabilitacoesPendentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habilitacao': {
      id: '/_authenticated/habilitacao'
      path: '/habilitacao'
      fullPath: '/habilitacao'
      preLoaderRoute: typeof AuthenticatedHabilitacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bnmp': {
      id: '/_authenticated/bnmp'
      path: '/bnmp'
      fullPath: '/bnmp'
      preLoaderRoute: typeof AuthenticatedBnmpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/': {
      id: '/_authenticated/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof AuthenticatedProcessosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/processos/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultas/$sistema': {
      id: '/_authenticated/consultas/$sistema'
      path: '/consultas/$sistema'
      fullPath: '/consultas/$sistema'
      preLoaderRoute: typeof AuthenticatedConsultasSistemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBnmpRoute: typeof AuthenticatedBnmpRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedHabilitacaoRoute: typeof AuthenticatedHabilitacaoRoute
  AuthenticatedHabilitacoesPendentesRoute: typeof AuthenticatedHabilitacoesPendentesRoute
  AuthenticatedIntimacoesRoute: typeof AuthenticatedIntimacoesRoute
  AuthenticatedMeusProcessosRoute: typeof AuthenticatedMeusProcessosRoute
  AuthenticatedNaoProtocoladosRoute: typeof AuthenticatedNaoProtocoladosRoute
  AuthenticatedNovoProcessoRoute: typeof AuthenticatedNovoProcessoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPautaAudienciasRoute: typeof AuthenticatedPautaAudienciasRoute
  AuthenticatedPrazosRoute: typeof AuthenticatedPrazosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedConsultasSistemaRoute: typeof AuthenticatedConsultasSistemaRoute
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
  AuthenticatedProcessosIndexRoute: typeof AuthenticatedProcessosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBnmpRoute: AuthenticatedBnmpRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedHabilitacaoRoute: AuthenticatedHabilitacaoRoute,
  AuthenticatedHabilitacoesPendentesRoute:
    AuthenticatedHabilitacoesPendentesRoute,
  AuthenticatedIntimacoesRoute: AuthenticatedIntimacoesRoute,
  AuthenticatedMeusProcessosRoute: AuthenticatedMeusProcessosRoute,
  AuthenticatedNaoProtocoladosRoute: AuthenticatedNaoProtocoladosRoute,
  AuthenticatedNovoProcessoRoute: AuthenticatedNovoProcessoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPautaAudienciasRoute: AuthenticatedPautaAudienciasRoute,
  AuthenticatedPrazosRoute: AuthenticatedPrazosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedConsultasSistemaRoute: AuthenticatedConsultasSistemaRoute,
  AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  AuthenticatedProcessosIndexRoute: AuthenticatedProcessosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsultaRoute: ConsultaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
